Setup and mobile version skeleton
magorsy26/Portfolio pull request #1
Opened 2022-06-30 11:43 UTC by magorsy26

In this section we have created the home page and add our description and the social media section.

2022-06-30 13:42 UTC, youmari requested changes
Hi @magorsy26 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Good commit messages
✔️ No linter error
✔️ Implementing the requirements

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 13:42 UTC, youmari commented on index.html
> +            <div>My Logo</div>
- [ ] Cause it's your logo  it would be better if you use the `<a>` tag instead of the `<div>` tag that will give a better sense and also will improve your SEO

2022-06-30 13:42 UTC, youmari commented on index.html
> +            <div><img src="Icons/Union.png" alt="burger icon" /></div>
- [ ] it would be better if you use the `<nav>` tag instead of the `<div>` tag that will give a better sense and also will improve your SEO

2022-06-30 13:42 UTC, youmari commented on index.html
> +        <div class="content">
- [ ] it would be better if you use the `<section>` tag instead of the `<div>` tag that will give a better sense and also will improve your SEO

2022-06-30 13:42 UTC, youmari commented on index.html
> +                    I’m Magor</span>
- [ ] it would be better if you use the `<h1>` tag instead of the `<span>` tag that will give a better sense and also will improve your SEO

2022-06-30 13:42 UTC, youmari commented on index.html
> +                <b>I’am a Software Developer</b>
- [ ] it would be better if you use the `<h2...6>` tag instead of the `<b>` tag that will give a better sense and also will improve your SEO

2022-06-30 13:42 UTC, youmari commented on index.html
> +            </div>
- [ ] please make sure that your social media icons are wrapped in `ul` tag and each one in `li` tag and the icon should be `<a>` tag
- one of your icons not displayed please fix that 
![image](https://user-images.githubusercontent.com/61790587/176691854-49a5f947-0d67-4950-bc20-385822bd850f.png)

2022-06-30 13:42 UTC, youmari commented on index.html
> +                </p>
- [ ] You should use the right font family for the title, subtitle, and the paragraph also the right font-size and the right margins in order to match the Figma design

2022-06-30 19:57 UTC, tresorsawasawa requested changes
# STATUS: REQUEST CHANGES :recycle::recycle: 

Hi @magorsy26 
Great work on making the changes requested by the previous reviewer  👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 19:57 UTC, tresorsawasawa commented on index.html
> +            </ul>
- [ ] Good job implementing some changes required by the previous reviewer. As mentioned by the previous reviewer, I noticed you are still having one broken image on your icons images. Pease makes sure you fix that to match the Figma design.
Here is what your social links images look like:
![Screenshot from 2022-06-30 21-37-57](https://user-images.githubusercontent.com/83042742/176763052-5be65f80-54b6-4641-86c2-bd52ee652072.png)

2022-06-30 19:57 UTC, tresorsawasawa commented on index.html
> +            <a href="#">My Logo</a>
- [ ] Good job implementing changes required by the previous reviewer. But I noticed that the logo text doesn't match the Figma design. Your logo text has underline decoration that is not on the Figma template. You can fix this by only adding this code to your `style.css` file: `a { text-decoration: none; }`

2022-06-30 19:57 UTC, tresorsawasawa commented on README.md
- [ **OPTIONAL** ] **IMPORTANT**: Kindly make sure you use your social link with username to make your README documentation professional. e.g:
```
GitHub: [@magorsy26](https://github.com/magorsy26)
```

2022-06-30 19:57 UTC, tresorsawasawa commented on README.md
- [ **OPTIONAL** ] **IMPORTANT**: I suggest you remove all unrelated sections of the project in your README and fill out the related(eg: `Getting Started: adding those commands you mentioned to clone the repo, Prerequisites tools,...)` sections to make your documentation professional. You can use **[this template](https://github.com/tresorsawasawa/MyPortfolio/blob/develop/README.md)** to help you correctly complete the related sections.

2022-07-01 08:22 UTC, KayLemba approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hello  @magorsy26       , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

HIGHLIGHTS:

- Your project is professional 
- Your repo is professional 
- Well structured files 


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

[OPTIONAL] Kindly add a screenshot to your README file showing your webpage user Interface. You can use extentions like fireshot to capturer the entire page.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-01 08:55 UTC, merged